apiVersion: v1
kind: ConfigMap
metadata:
  name: poc-api-config
  namespace: default
data:
  SPRING_DATASOURCE_URL: jdbc:h2:mem:testdb
  SPRING_DATASOURCE_USERNAME: sa
  SPRING_DATASOURCE_PASSWORD: password
  SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.H2Dialect
