apiVersion: v1
kind: Secret
metadata:
  name: poc-api-secret
  namespace: default
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: c2E=      # 'sa' em Base64
  SPRING_DATASOURCE_PASSWORD: cGFzc3dvcmQ= # 'password' em Base64